api/urls.py
from django.urls import path
from .views import (NseStockListView, NseStockCodeListView,
                    NseStockNameListView, PositionListView, UserFundListView, checkUserAuthenticated, WatchListView, WatchListCreateView, OrderListView,
                    OrderCreateView, OrderUpdateView, order_delete_view,
                    WatchListDeleteView, watchlist_item_delete_view, userLogout, UserKYCRetriveAPIView,
                    KYCDocumentNameListView,
                    UserBankDetailListView, UserBankDetailCreateView, UserBankDetailUpdateDeleteView,
                    )


urlpatterns = [

    path('positions/', PositionListView.as_view(), name="positions_list"),

    path("kyc/", UserKYCRetriveAPIView.as_view(), name="kyc_retrieve"),
    path("kyc_document_list/", KYCDocumentNameListView.as_view(),
         name="kyc_documents"),

    path('funds/', UserFundListView.as_view(), name="user_funds"),

    path("user/banks/", UserBankDetailListView.as_view(), name="user_banks"),
    path("user/bank/<int:pk>/", UserBankDetailUpdateDeleteView.as_view(), name="user_bank_detail_update_delete"),
    path("user/bank/create/", UserBankDetailCreateView.as_view(), name="user_bank_create"),

    path('orders/delete/<int:pk>/', order_delete_view, name="order_delete"),
    path('orders/update/<int:pk>/', OrderUpdateView.as_view(), name="order_update"),
    path('orders/create/', OrderCreateView.as_view(), name="order_create"),
    path('orders/', OrderListView.as_view(), name="order_list"),

    path('watchlist/item/delete/<str:code>/',
         watchlist_item_delete_view, name="watchlist_item_delete"),
    path('watchlist/delete/<int:pk>/',
         WatchListDeleteView.as_view(), name="watchlist_delete"),
    path('watchlist/create/', WatchListCreateView.as_view(),
         name="watch_list_create"),
    path('watchlist/', WatchListView.as_view(), name="watch_list"),

    path('stock/list/names/', NseStockNameListView.as_view(), name="stock_name_list"),
    path('stock/list/codes/', NseStockCodeListView.as_view(), name="stock_code_list"),
    path('stock/list/', NseStockListView.as_view(), name="stock_list"),
    path('user_authenticated/', checkUserAuthenticated,
         name="is_user_authenticated"),
    path("users/logout/", userLogout, name="userLogout")
]

users/urls.py
from django.urls import path, include, re_path
from dj_rest_auth.registration.views import VerifyEmailView
from allauth.account.views import ConfirmEmailView
from .views import login, register


urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('', include('dj_rest_auth.urls')),
    re_path(
        r'^accounts/register/account-confirm-email/(?P<key>[-:\w]+)/$', ConfirmEmailView.as_view(
        ),
        name='account_confirm_email',
    ),
    path('accounts/register/', include('dj_rest_auth.registration.urls')),
    path('account-confirm-email/', VerifyEmailView.as_view(),
         name="account_email_verification_sent"),
]

api/models.py
from attr import has
from django.db import models
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.urls import reverse
from django_lifecycle import LifecycleModelMixin, hook, AFTER_UPDATE, AFTER_CREATE
from simple_history.models import HistoricalRecords

from api.hook_utils import update_available_margin, send_notification

# Create your models here.
User = get_user_model()


class NseStock(models.Model):
    name = models.CharField(max_length=250)
    code = models.CharField(max_length=250)

    class Meta:
        ordering = ["id"]

    def __str__(self) -> str:
        return f"{self.name} ({self.code})"


class WatchList(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    stocks = models.ManyToManyField(NseStock)

    class Meta:
        ordering = ["id"]

    def __str__(self) -> str:
        return f"{self.user.first_name}'s watchlist."


class OrderStatus(models.Model):
    status = models.CharField(max_length=250)
    description = models.TextField(null=True, blank=True)
    message = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ["id"]

    def __str__(self) -> str:
        return f"{self.status}"

    def get_absolute_url(self):
        return reverse("backoffice_orderstatus_detail", kwargs={"pk": self.pk})


class OrderType(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ["id"]

    def __str__(self) -> str:
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse("backoffice_ordertype_detail", kwargs={"pk": self.pk})


class OrderAction(models.Model):
    action = models.CharField(max_length=250)
    description = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ["id"]

    def __str__(self) -> str:
        return f"{self.action}"

    def get_absolute_url(self):
        return reverse("backoffice_orderaction_detail", kwargs={"pk": self.pk})


class OrderProduct(models.Model):
    product = models.CharField(max_length=250)
    abbr = models.CharField(max_length=250, null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ["-id"]

    def __str__(self) -> str:
        return f"{self.product} - {self.description}"


class Position(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.PROTECT, blank=True, null=True)
    order = models.OneToOneField("Order", on_delete=models.PROTECT)
    is_exited = models.BooleanField(default=False)
    pl = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    ltp = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    history = HistoricalRecords()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        get_latest_by = ['-created_on', '-updated_on']
        ordering = ["-created_on", "-updated_on"]

    @hook(AFTER_UPDATE, when='is_exited', has_changed=True, is_now=True)
    def position_exited_stoploss_order_cancellation(self):
        print("Hook Called")
        if Position.objects.filter(order=self.order).exists():
            order_obj = get_object_or_404(Order, pk=self.order.id)
            cancelled_status_obj = OrderStatus.objects.get(status="Cancelled")
            order_obj.status = cancelled_status_obj
            order_obj.save()
            print("Order Changes Saved!")

    def __str__(self) -> str:
        return f"{self.order.order_id} - {self.is_exited}"


class Order(LifecycleModelMixin, models.Model):

    user = models.ForeignKey(User, on_delete=models.PROTECT)
    order_id = models.CharField(max_length=250, null=True, blank=True)
    stock = models.ForeignKey(NseStock, on_delete=models.PROTECT)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(decimal_places=2, max_digits=8)
    stop_loss = models.DecimalField(decimal_places=2, max_digits=8)
    margin = models.CharField(max_length=250, blank=True, null=True)
    order_type = models.ForeignKey(
        OrderType, on_delete=models.PROTECT, default=1, null=True, blank=True)
    action = models.ForeignKey(
        OrderAction, on_delete=models.PROTECT, null=True, blank=True)
    status = models.ForeignKey(
        OrderStatus, on_delete=models.PROTECT, default=1, null=True, blank=True)
    product = models.ForeignKey(
        OrderProduct, on_delete=models.PROTECT, null=True, blank=True)
    leverage = models.CharField(
        max_length=250, blank=True, null=True, default="2x")
    history = HistoricalRecords()
    is_deleted = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        get_latest_by = ['-created_on', '-updated_on']
        ordering = ["-created_on", "-updated_on"]

    @hook(AFTER_CREATE)
    @hook(AFTER_UPDATE, when='margin', has_changed=True)
    def available_margin_update(self):
        user = self.user
        fund_obj = UserFund.objects.filter(user=user)
        if fund_obj.exists():
            update_available_margin(
                fund_obj=fund_obj.first(), margin=self.margin)

    @hook(AFTER_UPDATE)
    def order_update_notification(self):
        admin_msg = f"{self.user.get_full_name()} has updated their order {self.order_id}"
        notification_type = "order_notification"

        if self.is_deleted:
            admin_msg = f"{self.user.get_full_name()} has deleted the order ({self.order_id})"


        send_notification('admin_notifications', admin_msg)
        send_notification('order_updates', "Order Updated!")

        admin_notification_obj = AdminNotifications(msg=admin_msg, notification_type=notification_type)
        admin_notification_obj.save()

    @hook(AFTER_UPDATE, when='status.status', has_changed=True, is_now="Executed")
    def create_order_position(self):
        print("Hook Called")
        if not Position.objects.filter(order=self).exists():
            print("Creating Order Position")
            Position.objects.create(order=self, user=self.user)
            print("Creating Order Position")

    def __str__(self) -> str:
        return f"{self.user.first_name} {self.stock.name} - ({self.created_on})"

    def get_absolute_url(self):
        return reverse("backoffice_order_detail", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse("backoffice_order_delete", kwargs={"pk": self.pk})


class GeneratedUUIDS(models.Model):
    name = models.IntegerField(blank=True, null=True)

    def __str__(self) -> str:
        return str(self.name)


def kyc_user_directory_path(instance, filename: str) -> str:
    """
    Defining the user directory when user uploads an file.

    instance: model instance (must contain user).
    filename: name of the file.
    """

    return 'user_{0}/{1}'.format(instance.user.id, filename)


class KYCDocumentName(models.Model):
    name = models.CharField(max_length=250)
    rule = models.CharField(max_length=250, blank=True, null=True)
    description = models.TextField(max_length=250, blank=True, null=True)

    def __str__(self) -> str:
        return f"{self.name} - {self.rule}"


class UserKYC(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_kyc_verified = models.BooleanField(default=False)
    history = HistoricalRecords()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("backoffice_kyc_detail", kwargs={"pk": self.pk})

    def __str__(self) -> str:
        return f"{self.user.email} (KYC) - {'Verified' if self.is_kyc_verified else 'Not Verified'}"


class UserDocument(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    kyc = models.ForeignKey(UserKYC, related_name='userkycdocuments',
                            on_delete=models.CASCADE, blank=True, null=True)
    number = models.CharField(
        max_length=250, blank=True, null=True, unique=True)
    document_name = models.ForeignKey(KYCDocumentName,
                                      on_delete=models.CASCADE,
                                      blank=True, null=True)
    document = models.FileField(upload_to=kyc_user_directory_path)
    remarks = models.TextField(null=True, blank=True)
    is_approved = models.BooleanField(default=False)
    history = HistoricalRecords()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"({self.user.email}) - {self.document_name}"


class UserFund(LifecycleModelMixin, models.Model):
    user = models.OneToOneField(
        User, related_name="userfunds", on_delete=models.CASCADE)
    available_margin = models.CharField(max_length=250, default=0.00)
    used_margin = models.CharField(max_length=250, default=0.00)
    available_cash = models.CharField(max_length=250, default=0.00)
    opening_balance = models.CharField(max_length=250, default=0.00)
    pay_in = models.CharField(max_length=250, default=0.00)
    pay_out = models.CharField(max_length=250, default=0.00)
    span = models.CharField(max_length=250, default=0.00)
    delivery_margin = models.CharField(max_length=250, default=0.00)
    exposure = models.CharField(max_length=250, default=0.00)
    options_premium = models.CharField(max_length=250, default=0.00)
    history = HistoricalRecords()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    @hook(AFTER_UPDATE)
    def notify_fund_change(self):
        send_notification('admin_fund_updates', "fund updated")

    class Meta:
        verbose_name = "User Fund"
        verbose_name_plural = "User Funds"

users/forms.py
from django import forms
from .mixins import BootStrapForm
from django.utils.translation import gettext_lazy as _


class AdminLoginForm(BootStrapForm):
    email = forms.EmailField(label=_("Email"), required=True)
    password = forms.CharField(label=_("Password"), required=True, widget=forms.PasswordInput())
    remember = forms.BooleanField(label=_("Remember Me"), required=False)

users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login as dj_login, logout
from django.contrib import messages
from django.views.decorators.http import require_POST

from .forms import AdminLoginForm

# Create your views here.


def login(request):
    return render(request, '_base.html')


def register(request):
    return render(request, '_base.html')

def admin_login(request):
    """
    Login view for admin
    """

    form = AdminLoginForm()
    if request.method == "POST":
        form = AdminLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['email']
            password = form.cleaned_data['password']
            remember = form.cleaned_data['remember']
            user = authenticate(request, username=username, password=password)
            if user is not None and user.is_staff:
                dj_login(request, user)
                if remember:
                    request.session.set_expiry(0)
                messages.success(request, "Login Successfull!")
                return redirect('backoffice_home')
            else:
                messages.error(request, "You don't have staff permissions to login, contact your administrator")
        else:
            messages.error(request, form.errors)
    return render(request, 'account/login.html', { 'form': form  })


@require_POST
def admin_logout(request):
    """
    Logout view for admin
    """

    logout(request)
    messages.success(request, "You have logged out successfully!")
    response = HttpResponseRedirect(reverse('backoffice_login'))
    response['HX-Redirect'] = reverse('backoffice_login')
    return response

templates/backoffice/forms/users/fund_form.html
<form action="" method="post">
  {% csrf_token %}
  <input type="hidden" value="{{object.user.id}}" name="user" />

  <div class="form-row">
    <div class="form-group col-md-4 col-sm-12">
      <label for="id_available_margin">Available Margin</label>
      <input
        id="id_available_margin"
        name="available_margin"
        placeholder="0.00"
        {% if object.available_margin %}
          value="{{object.available_margin}}"
        {% else %}
          value="0.00"
        {% endif %}
        type="text"
        aria-describedby="id_available_marginHelpBlock"
        required="required"
        class="form-control decimal"
      />
    </div>
    <div class="form-group col-md-4 col-sm-12">
      <label for="id_used_margin">Used Margin</label>
      <input
        id="id_used_margin"
        name="used_margin"
        placeholder="0.00"
        {% if object.used_margin %}
          value="{{object.used_margin}}"
        {% else %}
          value="0.00"
        {% endif %}
        type="text"
        class="form-control decimal"
      />
    </div>
    <div class="form-group col-md-4 col-sm-12">
      <label for="id_delivery_margin">Delivery Margin</label>
      <input
        id="id_delivery_margin"
        name="delivery_margin"
        placeholder="0.00"
        {% if object.delivery_margin %}
          value="{{object.delivery_margin}}"
        {% else %}
          value="0.00"
        {% endif %}
        type="text"
        class="form-control decimal"
      />
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6 col-sm-12">
      <label for="id_available_cash">Available Cash</label>
      <input
        id="id_available_cash"
        name="available_cash"
        placeholder="0.00"
        {% if object.available_cash %}
          value="{{object.available_cash}}"
        {% else %}
          value="0.00"
        {% endif %}
        type="text"
        class="form-control decimal"
      />
    </div>
    <div class="form-group col-md-6 col-sm-12">
      <label for="id_opening_balance">Opening balance</label>
      <input
        id="id_opening_balance"
        name="opening_balance"
        placeholder="0.00"
        {% if object.opening_balance %}
          value="{{object.opening_balance}}"
        {% else %}
          value="0.00"
        {% endif %}
        type="text"
        class="form-control decimal"
      />
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6 col-sm-12">
      <label for="id_pay_in">Pay In</label>
      <input
        id="id_pay_in"
        name="pay_in"
        placeholder="0.00"
        {% if object.pay_in %}
          value="{{object.pay_in}}"
        {% else %}
          value="0.00"
        {% endif %}
        type="text"
        class="form-control decimal"
      />
    </div>
    <div class="form-group col-md-6 col-sm-12">
      <label for="id_pay_out">Pay Out</label>
      <input
        id="id_pay_out"
        name="pay_out"
        placeholder="0.00"
        type="text"
        {% if object.pay_out %}
          value="{{object.pay_out}}"
        {% else %}
          value="0.00"
        {% endif %}
        class="form-control decimal"
      />
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-4 col-sm-12">
      <label for="id_span">Span</label>
      <input
        id="id_span"
        name="span"
        placeholder="0.00"
        {% if object.span %}
          value="{{object.span}}"
        {% else %}
          value="0.00"
        {% endif %}
        type="text"
        class="form-control decimal"
      />
    </div>
    <div class="form-group col-md-4 col-sm-12">
      <label for="id_exposure">Exposure</label>
      <input
        id="id_exposure"
        name="exposure"
        {% if object.exposure %}
          value="{{object.exposure}}"
        {% else %}
          value="0.00"
        {% endif %}
        placeholder="0.00"
        type="text"
        class="form-control decimal"
      />
    </div>
    <div class="form-group col-md-4 col-sm-12">
      <label for="id_options_premium">Options Premium</label>
      <input
        id="id_options_premium"
        name="options_premium"
        {% if object.options_premium %}
          value="{{object.options_premium}}"
        {% else %}
          value="0.00"
        {% endif %}
        placeholder="0.00"
        type="text"
        class="form-control decimal"
      />
    </div>
  </div>

  <div class="form-group">
    <button name="submit" type="submit" class="btn btn-primary">Submit</button>
  </div>
</form>

templates/backoffice/forms/users/user_bank.html
{% extends 'backoffice_base.html' %}

<!-- -->
{% block title %}{{ object.user.first_name }} - Bank{% endblock title %}

<!-- -->
{% block content %}
<h3>{{ object.user.get_full_name }} - Bank ({{ object.bank_name }}) 💰</h3>
<br />
<div class="card">
  <div class="card-body">
    <form action="" method="post">
      {% csrf_token %}
      <!-- Form -->
      {{ form }}
      <br />
      <button class="btn btn-success" type="submit">Submit</button>
    </form>
  </div>
</div>
<hr />
<div class="card">
  <div class="card-body">
    <div class="table-responsive">
      <table id="all_users_funds" class="table table-bordered table-sm">
        <thead class="thead-dark">
          <tr>
            <th>Full Name</th>
            <th>Email</th>
            <th>Mobile Number</th>
            <th>Bank Name</th>
            <th>Account No</th>
            <th>IFSC code</th>
            <th>Created At</th>
            <th>Updated At</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>{{ object.user.get_full_name }}</td>
            <td>{{ object.user.email }}</td>
            <td>{{ object.user.mobile_number }}</td>
            <td>{{ object.bank_name }}</td>
            <td>{{ object.account_number }}</td>
            <td>{{ object.ifsc_code }}</td>
            <td>{{ object.created_at }}</td>
            <td>{{ object.updated_at }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock content %}

templates/backoffice/forms/users/user_fund.html
{% extends 'backoffice_base.html' %}

<!-- -->
{% block title %}{{ object.user.first_name }} - funds{% endblock title %}

<!-- -->
{% block content %}
<h3>{{ object.user.get_full_name }} - Funds 💰</h3>
<br />
<div class="card">
  <div class="card-body">
    {% include 'backoffice/forms/users/fund_form.html' %}
  </div>
</div>
<hr />
<div class="card">
  <div class="card-body">
    <div class="table-responsive">
      <table id="user_fund" class="table table-bordered table-sm">
        <thead class="thead-dark">
          <tr>
            <th>Full Name</th>
            <th>Email</th>
            <th>Mobile Number</th>
            <th>available_margin</th>
            <th>used_margin</th>
            <th>available_cash</th>
            <th>opening_balance</th>
            <th>pay_in</th>
            <th>pay_out</th>
            <th>span</th>
            <th>delivery_margin</th>
            <th>options_premium</th>
            <th>updated on</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>{{ object.user.get_full_name }}</td>
            <td>{{ object.user.email }}</td>
            <td>{{ object.user.mobile_number }}</td>
            <td>{{ object.available_margin }}</td>
            <td>{{ object.used_margin }}</td>
            <td>{{ object.opening_balance }}</td>
            <td>{{ object.pay_in }}</td>
            <td>{{ object.pay_out }}</td>
            <td>{{ object.span }}</td>
            <td>{{ object.delivery_margin }}</td>
            <td>{{ object.exposure }}</td>
            <td>{{ object.options_premium }}</td>
            <td>{{ object.updated_on }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock content %}