api/urls.py
from django.urls import path
from .views import (NseStockListView, NseStockCodeListView,
                    NseStockNameListView, PositionListView, UserFundListView, checkUserAuthenticated, WatchListView, WatchListCreateView, OrderListView,
                    OrderCreateView, OrderUpdateView, order_delete_view,
                    WatchListDeleteView, watchlist_item_delete_view, userLogout, UserKYCRetriveAPIView,
                    KYCDocumentNameListView,
                    UserBankDetailListView, UserBankDetailCreateView, UserBankDetailUpdateDeleteView,
                    )


urlpatterns = [

    path('positions/', PositionListView.as_view(), name="positions_list"),

    path("kyc/", UserKYCRetriveAPIView.as_view(), name="kyc_retrieve"),
    path("kyc_document_list/", KYCDocumentNameListView.as_view(),
         name="kyc_documents"),

    path('funds/', UserFundListView.as_view(), name="user_funds"),

    path("user/banks/", UserBankDetailListView.as_view(), name="user_banks"),
    path("user/bank/<int:pk>/", UserBankDetailUpdateDeleteView.as_view(), name="user_bank_detail_update_delete"),
    path("user/bank/create/", UserBankDetailCreateView.as_view(), name="user_bank_create"),

    path('orders/delete/<int:pk>/', order_delete_view, name="order_delete"),
    path('orders/update/<int:pk>/', OrderUpdateView.as_view(), name="order_update"),
    path('orders/create/', OrderCreateView.as_view(), name="order_create"),
    path('orders/', OrderListView.as_view(), name="order_list"),

    path('watchlist/item/delete/<str:code>/',
         watchlist_item_delete_view, name="watchlist_item_delete"),
    path('watchlist/delete/<int:pk>/',
         WatchListDeleteView.as_view(), name="watchlist_delete"),
    path('watchlist/create/', WatchListCreateView.as_view(),
         name="watch_list_create"),
    path('watchlist/', WatchListView.as_view(), name="watch_list"),

    path('stock/list/names/', NseStockNameListView.as_view(), name="stock_name_list"),
    path('stock/list/codes/', NseStockCodeListView.as_view(), name="stock_code_list"),
    path('stock/list/', NseStockListView.as_view(), name="stock_list"),
    path('user_authenticated/', checkUserAuthenticated,
         name="is_user_authenticated"),
    path("users/logout/", userLogout, name="userLogout")
]

api/models.py
from attr import has
from django.db import models
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.urls import reverse
from django_lifecycle import LifecycleModelMixin, hook, AFTER_UPDATE, AFTER_CREATE
from simple_history.models import HistoricalRecords

from api.hook_utils import update_available_margin, send_notification

# Create your models here.
User = get_user_model()


class NseStock(models.Model):
    name = models.CharField(max_length=250)
    code = models.CharField(max_length=250)

    class Meta:
        ordering = ["id"]

    def __str__(self) -> str:
        return f"{self.name} ({self.code})"


class WatchList(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    stocks = models.ManyToManyField(NseStock)

    class Meta:
        ordering = ["id"]

    def __str__(self) -> str:
        return f"{self.user.first_name}'s watchlist."


class OrderStatus(models.Model):
    status = models.CharField(max_length=250)
    description = models.TextField(null=True, blank=True)
    message = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ["id"]

    def __str__(self) -> str:
        return f"{self.status}"

    def get_absolute_url(self):
        return reverse("backoffice_orderstatus_detail", kwargs={"pk": self.pk})


class OrderType(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ["id"]

    def __str__(self) -> str:
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse("backoffice_ordertype_detail", kwargs={"pk": self.pk})


class OrderAction(models.Model):
    action = models.CharField(max_length=250)
    description = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ["id"]

    def __str__(self) -> str:
        return f"{self.action}"

    def get_absolute_url(self):
        return reverse("backoffice_orderaction_detail", kwargs={"pk": self.pk})


class OrderProduct(models.Model):
    product = models.CharField(max_length=250)
    abbr = models.CharField(max_length=250, null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ["-id"]

    def __str__(self) -> str:
        return f"{self.product} - {self.description}"


class Position(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.PROTECT, blank=True, null=True)
    order = models.OneToOneField("Order", on_delete=models.PROTECT)
    is_exited = models.BooleanField(default=False)
    pl = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    ltp = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    history = HistoricalRecords()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        get_latest_by = ['-created_on', '-updated_on']
        ordering = ["-created_on", "-updated_on"]

    @hook(AFTER_UPDATE, when='is_exited', has_changed=True, is_now=True)
    def position_exited_stoploss_order_cancellation(self):
        print("Hook Called")
        if Position.objects.filter(order=self.order).exists():
            order_obj = get_object_or_404(Order, pk=self.order.id)
            cancelled_status_obj = OrderStatus.objects.get(status="Cancelled")
            order_obj.status = cancelled_status_obj
            order_obj.save()
            print("Order Changes Saved!")

    def __str__(self) -> str:
        return f"{self.order.order_id} - {self.is_exited}"


class Order(LifecycleModelMixin, models.Model):

    user = models.ForeignKey(User, on_delete=models.PROTECT)
    order_id = models.CharField(max_length=250, null=True, blank=True)
    stock = models.ForeignKey(NseStock, on_delete=models.PROTECT)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(decimal_places=2, max_digits=8)
    stop_loss = models.DecimalField(decimal_places=2, max_digits=8)
    margin = models.CharField(max_length=250, blank=True, null=True)
    order_type = models.ForeignKey(
        OrderType, on_delete=models.PROTECT, default=1, null=True, blank=True)
    action = models.ForeignKey(
        OrderAction, on_delete=models.PROTECT, null=True, blank=True)
    status = models.ForeignKey(
        OrderStatus, on_delete=models.PROTECT, default=1, null=True, blank=True)
    product = models.ForeignKey(
        OrderProduct, on_delete=models.PROTECT, null=True, blank=True)
    leverage = models.CharField(
        max_length=250, blank=True, null=True, default="2x")
    history = HistoricalRecords()
    is_deleted = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        get_latest_by = ['-created_on', '-updated_on']
        ordering = ["-created_on", "-updated_on"]

    @hook(AFTER_CREATE)
    @hook(AFTER_UPDATE, when='margin', has_changed=True)
    def available_margin_update(self):
        user = self.user
        fund_obj = UserFund.objects.filter(user=user)
        if fund_obj.exists():
            update_available_margin(
                fund_obj=fund_obj.first(), margin=self.margin)

    @hook(AFTER_UPDATE)
    def order_update_notification(self):
        admin_msg = f"{self.user.get_full_name()} has updated their order {self.order_id}"
        notification_type = "order_notification"

        if self.is_deleted:
            admin_msg = f"{self.user.get_full_name()} has deleted the order ({self.order_id})"


        send_notification('admin_notifications', admin_msg)
        send_notification('order_updates', "Order Updated!")

        admin_notification_obj = AdminNotifications(msg=admin_msg, notification_type=notification_type)
        admin_notification_obj.save()

    @hook(AFTER_UPDATE, when='status.status', has_changed=True, is_now="Executed")
    def create_order_position(self):
        print("Hook Called")
        if not Position.objects.filter(order=self).exists():
            print("Creating Order Position")
            Position.objects.create(order=self, user=self.user)
            print("Creating Order Position")

    def __str__(self) -> str:
        return f"{self.user.first_name} {self.stock.name} - ({self.created_on})"

    def get_absolute_url(self):
        return reverse("backoffice_order_detail", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse("backoffice_order_delete", kwargs={"pk": self.pk})


class GeneratedUUIDS(models.Model):
    name = models.IntegerField(blank=True, null=True)

    def __str__(self) -> str:
        return str(self.name)


def kyc_user_directory_path(instance, filename: str) -> str:
    """
    Defining the user directory when user uploads an file.

    instance: model instance (must contain user).
    filename: name of the file.
    """

    return 'user_{0}/{1}'.format(instance.user.id, filename)


class KYCDocumentName(models.Model):
    name = models.CharField(max_length=250)
    rule = models.CharField(max_length=250, blank=True, null=True)
    description = models.TextField(max_length=250, blank=True, null=True)

    def __str__(self) -> str:
        return f"{self.name} - {self.rule}"


class UserKYC(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_kyc_verified = models.BooleanField(default=False)
    history = HistoricalRecords()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("backoffice_kyc_detail", kwargs={"pk": self.pk})

    def __str__(self) -> str:
        return f"{self.user.email} (KYC) - {'Verified' if self.is_kyc_verified else 'Not Verified'}"


class UserDocument(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    kyc = models.ForeignKey(UserKYC, related_name='userkycdocuments',
                            on_delete=models.CASCADE, blank=True, null=True)
    number = models.CharField(
        max_length=250, blank=True, null=True, unique=True)
    document_name = models.ForeignKey(KYCDocumentName,
                                      on_delete=models.CASCADE,
                                      blank=True, null=True)
    document = models.FileField(upload_to=kyc_user_directory_path)
    remarks = models.TextField(null=True, blank=True)
    is_approved = models.BooleanField(default=False)
    history = HistoricalRecords()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"({self.user.email}) - {self.document_name}"


class UserFund(LifecycleModelMixin, models.Model):
    user = models.OneToOneField(
        User, related_name="userfunds", on_delete=models.CASCADE)
    available_margin = models.CharField(max_length=250, default=0.00)
    used_margin = models.CharField(max_length=250, default=0.00)
    available_cash = models.CharField(max_length=250, default=0.00)
    opening_balance = models.CharField(max_length=250, default=0.00)
    pay_in = models.CharField(max_length=250, default=0.00)
    pay_out = models.CharField(max_length=250, default=0.00)
    span = models.CharField(max_length=250, default=0.00)
    delivery_margin = models.CharField(max_length=250, default=0.00)
    exposure = models.CharField(max_length=250, default=0.00)
    options_premium = models.CharField(max_length=250, default=0.00)
    history = HistoricalRecords()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    @hook(AFTER_UPDATE)
    def notify_fund_change(self):
        send_notification('admin_fund_updates', "fund updated")

    class Meta:
        verbose_name = "User Fund"
        verbose_name_plural = "User Funds"

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      rel="icon"
      href="{% static 'favicon/favicon.ico' %}"
      type="image/x-icon"
    />

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;0,800;1,300;1,400;1,600;1,700&display=swap"
      rel="stylesheet"
    />

    <!-- Index CSS -->
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />

    {% block custom_head %}{% endblock custom_head %}

    <title>{% block title_content %}{% endblock title_content %}</title>
  </head>
  <body>
    <div id="app"></div>

    <script src="{% static 'js/main.js' %}"></script>
    {% block custom_script %}{% endblock custom_script %}
  </body>
</html>

templates/backoffice_base.html
{% load static %}
<!-- -->
{% load custom_tags %}
<!-- -->
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      rel="icon"
      href="{% static 'favicon/favicon.ico' %}"
      type="image/x-icon"
    />

    <!-- core:css -->
    <link rel="stylesheet" href="{% static 'vendors/core/core.css' %}" />

    <link rel="stylesheet" src="{% static 'vendors/select2/select2.min.css' %}">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <link
      rel="stylesheet"
      href="{% static 'vendors/bootstrap-datepicker/bootstrap-datepicker.min.css' %}"
    />
    <!-- end plugin css for this page -->
    <!-- inject:css -->
    <link
      rel="stylesheet"
      href="{% static 'fonts/feather-font/css/iconfont.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'vendors/flag-icon-css/css/flag-icon.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'vendors/mdi/css/materialdesignicons.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'vendors/sweetalert2/sweetalert2.min.css' %}"
    />
    <link rel="stylesheet" href="{% static 'vendors/jquery-tags-input/jquery.tagsinput.min.css' %}">

    <link rel="stylesheet" href="{% static 'vendors/dropzone/dropzone.min.css' %}">

    <link rel="stylesheet" href="{% static 'vendors/dropify/dist/dropify.min.css' %}">

    <link rel="stylesheet" href="{% static 'vendors/bootstrap-colorpicker/bootstrap-colorpicker.min.css' %}">

    <link rel="stylesheet" href="{% static 'vendors/bootstrap-datepicker/bootstrap-datepicker.min.css' %}">

    <link rel="stylesheet" href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}">


    <!-- endinject -->

    <!-- Layout styles -->
    <link rel="stylesheet" href="{% static 'css/backoffice/style.min.css' %}" />
    <!-- End layout styles -->

    <link rel="stylesheet" href="{% static 'css/backoffice/index.css' %}" />
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />

    {% comment %} <!-- Alpine.js -->
    <script defer src="{% static 'js/alpine.min.js' %}"></script> {% endcomment %}

    <link rel="stylesheet" href="{% static 'vendors/tempusdominus-bootstrap-4/tempusdominus-bootstrap-4.min.css' %}" />

    <link rel="stylesheet" href="{% static 'vendors/datatables.net-bs4/dataTables.bootstrap4.css' %}" />
    <link rel="stylesheet" href="{% static 'vendors/dropzone/dropzone.min.css' %}" />

    <style>
      .card-header {
        padding: 5px;
      }

      .empty_form {
        display: none;
      }

      select {
        color: #4d4d4d;
      }
    </style>

    {% block custom_style %}{% endblock custom_style %}

    <title> {% block title %} {% endblock title %} |
    {% if company.name %}
      {{ company.name }}
    {% else %}
      BackOffice
    {% endif %}
    </title>
  </head>
  <body>

    {% block company_select %}
    {% endblock company_select %}
    <div class="main-wrapper">
      <!--  partial:partials/_sidebar.html -->
      {% include 'partials/_sidebar.html' %} 
      <!-- END ** partial:partials/_sidebar.html ** END -->

      <div class="page-wrapper">
        <!-- partial:partials/_navbar.html -->
        {% include 'partials/_navbar.html' %}
        <!-- END ** partial:partials/_navbar.html ** END -->

        <div id="click_element" class="page-content">
          {% block content %} {% endblock content %}
        </div>
      </div>
    </div>
   

    <!-- core:js -->

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/backoffice/main.js' %}"></script>
    <script src="{% static 'vendors/core/core.js' %}"></script>
    <!-- endinject -->
    <script src="{% static 'vendors/datatables.net/jquery.dataTables.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-bs4/dataTables.bootstrap4.js' %}"></script>
    <!-- plugin js for this page -->
    <script src="{% static 'vendors/select2/select2.min.js' %}"></script>
    <script src="{% static 'vendors/chartjs/Chart.min.js' %}"></script>
    <script src="{% static 'vendors/jquery.flot/jquery.flot.js' %}"></script>
    <script src="{% static 'vendors/jquery.flot/jquery.flot.resize.js' %}"></script>
    <script src="{% static 'vendors/bootstrap-datepicker/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'vendors/apexcharts/apexcharts.min.js' %}"></script>
    <script src="{% static 'vendors/jquery-validation/jquery.validate.min.js' %}"></script>
    <script src="{% static 'vendors/bootstrap-maxlength/bootstrap-maxlength.min.js' %}"></script>
    <script src="{% static 'vendors/progressbar.js/progressbar.min.js' %}"></script>
    <script src="{% static 'vendors/sweetalert2/sweetalert2.min.js' %}"></script>
    <!-- end plugin js for this page -->
    <!-- inject:js -->
    <script src="{% static 'vendors/feather-icons/feather.min.js' %}"></script>
    <script src="{% static 'vendors/dropzone/dropzone.min.js' %}"></script>
    <script src="{% static 'vendors/inputmask/jquery.inputmask.min.js' %}"></script>
    <script src="{% static 'js/template.js' %}"></script>
    <!-- endinject -->
    <!-- custom js for this page -->
    <script src="{% static 'js/dashboard.js' %}"></script>
    <script src="{% static 'js/datepicker.js' %}"></script>

    <!-- htmx -->
    <script src="{% static 'js/htmx.min.js' %}"></script>
    <script src="{% static 'js/backoffice/custom.js' %}"></script>
    <!-- <script src="{% static 'js/backoffice/admin_fund_updates.js' %}"></script> -->
    <script src="{% static 'js/backoffice/order_notifications.js' %}"></script>
    <script src="https://unpkg.com/hyperscript.org@0.9.4"></script>
    <script src="{% static 'js/index.js' %}"></script>
    <script src="{% static 'js/backoffice/admin_notifications.js' %}"></script>

    <!-- end custom js for this page -->
    <!-- Sweet Alert notification -->
    <script>
    // Display messages from server as status messages.
    {% if messages %}
        {% for message in messages %}
            const Toast = Swal.mixin({
                toast: true,
                position: 'top-end',
                showConfirmButton: false,
                timer: 5000,
                timerProgressBar: true,
                didOpen: (toast) => {
                    toast.addEventListener('mouseenter', Swal.stopTimer)
                    toast.addEventListener('mouseleave', Swal.resumeTimer)
                }
            })

            Toast.fire({
              icon: '{{ message.level_tag|safe }}',
              title: '{{ message|safe }}'
            })
        {% endfor %}
    {% endif %}
    </script>
    <!-- Sweet Alert notification end -->

    <script>
        // Adding CSRF token to HTMX post requests (DO NOT DELETE THIS).
        document.body.addEventListener('htmx:configRequest', (event) => {
          event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
        });

        // Add Extra formset
        const addForm = (e) => {
          const el = e.target.parentElement;

          const total_forms = el.querySelector("input[name*='TOTAL_FORMS']");

          let no_of_forms = parseInt(total_forms.value) + 1;


          // const regex = /\d+/
          const regex = RegExp(/__prefix__/, 'g');

          total_forms.value = no_of_forms;

          let clone_target_el = el.querySelector('.empty_form')

          const HR = document.createElement('hr')

          let newForm = clone_target_el.cloneNode(true);

          newForm.classList.remove('empty_form')
          newForm.classList.add('mt-2');

          newForm.innerHTML = newForm.innerHTML.replace(regex, `${no_of_forms - 1}`)

          el.insertBefore(newForm, e.target)
          newForm.insertAdjacentElement('beforeBegin', HR);
        }

        // HTMX Trigger for updating the table when changes in db.
        document.body.addEventListener('update-table', () => {
          htmx.trigger('#table_card', 'update-table')
        })

      </script>
      {% block custom_script %}{% endblock custom_script %}
  </body>
</html>

templates/notifications.html
<!-- Sweet Alert notification -->
{% load static %}
<script src="{% static 'vendors/sweetalert2/sweetalert2.min.js' %}"></script>
<script>
  // Display messages from server as status messages.
  {% if messages %}
      {% for message in messages %}
          const Toast = Swal.mixin({
              toast: true,
              position: 'top-end',
              showConfirmButton: false,
              timer: 4000,
              timerProgressBar: true,
              didOpen: (toast) => {
                  toast.addEventListener('mouseenter', Swal.stopTimer)
                  toast.addEventListener('mouseleave', Swal.resumeTimer)
              }
          })

          Toast.fire({
            icon: '{{ message.level_tag|safe }}',
            title: '{{ message|safe }}'
          })
      {% endfor %}
  {% endif %}
</script>
<!-- Sweet Alert notification end -->

templates/user_document_upload.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KYC Document Upload</title>
    <link rel="stylesheet" href="{% static 'vendors/core/core.css' %}" />
    <link rel="stylesheet" href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}">
    <!-- Layout styles -->
    <link rel="stylesheet" href="{% static 'css/backoffice/style.min.css' %}" />
    <!-- End layout styles -->
    <link rel="stylesheet" href="{% static 'vendors/tempusdominus-bootstrap-4/tempusdominus-bootstrap-4.min.css' %}" />

    <link
      rel="stylesheet"
      href="{% static 'vendors/sweetalert2/sweetalert2.min.css' %}"
    />

    <link rel="stylesheet" href="{% static 'css/backoffice/index.css' %}" />
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <form action="{% url 'user_kyc_upload' object.id %}" enctype="multipart/form-data" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="kyc" value="{{ object.id }}" />
                            <input type="hidden" name="user" value="{{ object.user.id }}" />
                            <div class="form-group">
                                <label for="document_name">Document Type</label>
                                <div>
                                <select id="document_name" required name="document_name" class="custom-select required"
                                    aria-describedby="document_nameHelpBlock" required="required">
                                    <option selected>Select Document Type</option>

                                    {% for document in document_names %}
                                    <option value="{{document.id}}">{{ document.name }}</option>
                                    {% endfor %}
                                </select>
                                </div>
                            </div>
                            <div id="document_form_toggle" style="display: none">
                                <div class="form-group">
                                <label for="id_number">Number</label>
                                <input id="id_number" required name="number" placeholder="number" type="text" class="form-control required"
                                    aria-describedby="numberHelpBlock" />
                                </div>
                                <div class="form-group">
                                <div class="col-lg-4">
                                    <label for="id_document">Document</label>
                                    <input type="file" class="form-control" id="id_document" name="document" />
                                </div>
                                </div>
                                <button class="btn btn-success">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                <div class="card-body">
                    <h5 class="card-title text-danger">Uploaded Documents</h5>
                    <hr>
                    <div class="table-responsive">
                    {% include 'backoffice/tables/kyc/kyc_detail_table.html' %}
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/backoffice/main.js' %}"></script>
    <script src="{% static 'vendors/core/core.js' %}"></script>
    <!-- endinject -->
    <script src="{% static 'vendors/datatables.net/jquery.dataTables.js' %}"></script>
    <script src="{% static 'vendors/datatables.net-bs4/dataTables.bootstrap4.js' %}"></script>
    <!-- plugin js for this page -->
    <script src="{% static 'vendors/select2/select2.min.js' %}"></script>
    <script src="{% static 'vendors/chartjs/Chart.min.js' %}"></script>
    <script src="{% static 'vendors/jquery.flot/jquery.flot.js' %}"></script>
    <script src="{% static 'vendors/jquery.flot/jquery.flot.resize.js' %}"></script>
    <script src="{% static 'vendors/bootstrap-datepicker/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'vendors/apexcharts/apexcharts.min.js' %}"></script>
    <script src="{% static 'vendors/jquery-validation/jquery.validate.min.js' %}"></script>
    <script src="{% static 'vendors/bootstrap-maxlength/bootstrap-maxlength.min.js' %}"></script>
    <script src="{% static 'vendors/progressbar.js/progressbar.min.js' %}"></script>
    <script src="{% static 'vendors/sweetalert2/sweetalert2.min.js' %}"></script>
    <!-- end plugin js for this page -->
    <!-- inject:js -->
    <script src="{% static 'vendors/feather-icons/feather.min.js' %}"></script>
    <script src="{% static 'vendors/dropzone/dropzone.min.js' %}"></script>
    <script src="{% static 'vendors/inputmask/jquery.inputmask.min.js' %}"></script>
    <script src="{% static 'js/template.js' %}"></script>
    <!-- endinject -->
    <!-- custom js for this page -->
    <script src="{% static 'js/dashboard.js' %}"></script>
    <script src="{% static 'js/datepicker.js' %}"></script>

    <!-- htmx -->
    <script src="{% static 'js/htmx.min.js' %}"></script>
    <script src="{% static 'js/backoffice/custom.js' %}"></script>
    <script src="https://unpkg.com/hyperscript.org@0.9.4"></script>
    <script src="{% static 'js/index.js' %}"></script>
    <!-- Sweet Alert notification -->
    <script>
    // Display messages from server as status messages.
    {% if messages %}
        {% for message in messages %}
            const Toast = Swal.mixin({
                toast: true,
                position: 'top-end',
                showConfirmButton: false,
                timer: 5000,
                timerProgressBar: true,
                didOpen: (toast) => {
                    toast.addEventListener('mouseenter', Swal.stopTimer)
                    toast.addEventListener('mouseleave', Swal.resumeTimer)
                }
            })

            Toast.fire({
              icon: '{{ message.level_tag|safe }}',
              title: '{{ message|safe }}'
            })
        {% endfor %}
    {% endif %}
    </script>
</body>
</html>